---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Load the FAS Litters data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
litters_df
```

## `select`

Choose some columns and not others.

```{r}
select(litters_df, group, gd0_weight)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

Renaming columns:

```{r}
select(litters_df, GROUP = group, LITTER_number = litter_number)
```

```{r}
rename(litters_df, poop = group, litnum = litter_number)
```

`select` helpers

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

## `filter`

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
```

```{r}
filter(litters_df, gd_of_birth != 20)
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Con7")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8"))
```

## `mutate`

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
  )
```

## `arrange`

```{r}
arrange(litters_df, pups_born_alive)
```







